#server config
server.port=${PORT:8004}

# DB config
spring.datasource.url={DB_URL}
spring.datasource.username={DB_UNAME]
spring.datasource.password={DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://dpg-d5l6uvcoud1c73834840-a.singapore-postgres.render.com:5432/budget_bab?sslmode=require
#spring.datasource.username=budget_bab_user
#spring.datasource.password=RqEOiLV9Oo83myunucEApqxmVsTIExiv
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api/v1.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#email config
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME:}
spring.mail.password=${BREVO_PASSWORD:}
spring.mail.properties.mail.from=${BREVO_FROM_EMAIL:noreply@bugetbaba.com}
brevo.api.key=${BREVO_API_KEY:disabled}
brevo.api.url=https://api.brevo.com/v3/smtp/email

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=30000

#jwt
spring.jwt.secret=4f9d3e7c1b5a2f8d6c0e1a7b9d3f6c2e8b7a1c9e5f0d4b2a6c3e8f1d7a5b9c0
spring.jwt.expiration=36000000

#url
buget.baba.frontend.url=${Buget_BABA_FRONTEND_URL}
app.activation.url=${BUGET_BABA_BACKEND_URL}
